name: Package autoscripts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tar_directories:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Tgz directories
      run: |
        cd src
        for dir in ./*; do
          echo $dir
          if [ -d "$dir" ]; then
            pkgname=$(basename $dir) 
            tar -czvf ../packages/${pkgname}.tgz $dir
          fi
        done

    - name: Generate manifest
      run: |
        echo "[" > manifest
        for dir in src/*; do
          if [ -d $dir ]; then
            cd "$dir"
            name=$(jq -r '.name' manifest.json)
            version_major=$(jq -r '.version_major' manifest.json)
            version_minor=$(jq -r '.version_minor' manifest.json)
            description=$(jq -r '.description' manifest.json)
            cd ../..
            echo "{\"name\":\"$name\",\"version_major\":\"$version_major\",\"version_minor\":\"$version_minor\",\"description\":\"$description\"}," >> manifest
          fi
        done
        asmajor=$(grep "set asmajor" autoscripts.tcl| awk '{print $3}')
        asminor=$(grep "set asminor" autoscripts.tcl| awk '{print $3}')
        echo "{\"name\":\"autoscripts\",\"version_major\":\"$asmajor\",\"version_minor\":\"$asminor\",\"description\":\"Eggdrop autoscripts\"}" >> manifest
        echo "]" >> manifest

    - name: Commit autoscripts packages
      uses: EndBug/add-and-commit@v9
      with:
        add: './packages/*.tgz manifest'
        author_name: Eggheads Autoscripts
        author_email: geo@eggheads.org
        default_author: user_info
        message: Update autoscripts
        push: true
